#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Prevent pushing to main branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "main" ]; then
  echo "You can't push directly to the main branch. Please create a pull request instead."
  exit 1
fi
